require: ts-node/register
reporter: spec
delay: true
retries: 1
exit: true
spec:
  - test/e2e/delay.spec.ts
  - test/**/*.spec.ts
  # - test/engine/conditions.spec.ts
  # - test/engine/conditions.spec.ts
  # - test/dialogue/sorted.spec.ts
